### ISSUE TITLE
Bootstrap API shim and implement V3/Global root endpoints

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#1]
## Description

Create the initial structure of the API Shim and begin fleshing out its README with instructions on how to run it locally. The [V3 root endpoints](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#root), `/` and `/v3`, are convenient ones to get us started with since they do not rely on any authentication or persistent state (custom resources).

### README Instructions

**GIVEN** I have the CF API Shim repo
**WHEN** I follow steps in the README to run the shim locally
**THEN** I can curl the API locally

---

### Global Root Endpoint `/`
**GIVEN** I have the shim running locally
**WHEN** I `GET localhost:9000/` (`9000` is just an example. Actual port should be configurable.)
**THEN** I get back the following response
```json
{
  "links": {
    "self": {
      "href": "localhost". <------------ server needs to know its address, this should be configurable
    },
    "bits_service": null,
    "cloud_controller_v2": null,
    "cloud_controller_v3": {
      "href": "https://api.example.org/v3",
      "meta": {
        "version": "3.90.0" <------------ TODO: figure out what version should be in a future story
      }
    },
    "network_policy_v0": null,
    "network_policy_v1": null,
    "login": null,
    "uaa": null,
    "credhub": null,
    "routing": null,
    "logging": null,
    "log_cache": null,
    "log_stream": null,
    "app_ssh": null
  }
}
```

---

### V3 Root Endpoint `/v3`

This one will start pretty empty for now and we can add resources to it as we implement them. It's unclear if clients will prefer absent resources or `null`, though, but for now this is fine.

**GIVEN** I have the shim running locally
**WHEN** I `get localhost:9000/v3`
**THEN** I get back the following response
```json
{
  "links": {
    "self": {
      "href": "https://api.example.org/v3"
    }
  }
}
```

---

## Dev Notes

* We should include testing and set up the testing framework
* These endpoints do not require any of the CRDs yet. Mostly information to return to the user.
* This excludes the `/v2/info` endpoint. That will be added in a later story.

**Docs for these endpoints:**
 * https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#root
 * https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#global-api-root
 * https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#v3-api-root

**Comment by gcapizzi** [comment]
👋  @tcdowney we are thinking about implementing `cf api` on k8s and:

* we'll need to identify it's a CF on K8s foundation
* we'll need to know which `context` to use from `$KUBECONFIG`

In order to do those things, we need to know the URL of the Kubernetes cluster we're working against. It's definitely a piece of information the shim should be aware of.

Shall we have a separate story to add it as a field in the root payload? Any ideas about how to call such a field and where to put it? It probably belongs to `links`, so maybe something like this?

```json
{
  "links": {
    "...": "...",
    "kubernetes": {
      "href": "xxx"
    }
  }
}
```

**Comment by tcdowney** [comment]
@gcapizzi yeah that sounds good. It should go on the [Global API Root](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#global-api-root) (clients use this for discovery of other APIs) and belongs in `links` like you suggested (for posterity, here's the [style guide for links](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md#links)).

Naming is the trickiest part... `kubernetes` probably makes sense. At least in a world where there is a `1-to-1` mapping between shims and clusters which is what we're targeting initially. It probably still makes sense in a potential multi-cluster future since I imagine there would still be a "main" cluster type thing (@acosta11 something to chew on).

**Comment by gcapizzi** [comment]
> It probably still makes sense in a potential multi-cluster future since I imagine there would still be a "main" cluster type thing

Yes I thought about this too, it's tricky! So far we've planned to keep all authentication information on the client side, but this means that the client needs to have auth info for every cluster and know which one to send to the shim every time. I can see it working if the multiple clusters all share the same authentication, or something like Pinniped is in place. Anyway, I'll drop an explore for this!
