### ISSUE TITLE
[Bug]: address flaky test comment

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/cf-k8s-api#103]
### What happened?

There is a comment [here](https://github.com/cloudfoundry/cf-k8s-api/blob/da178a145182a69c5c51d4c98585be29bd34bfe2/repositories/app_repository_test.go#L545) mentioning a flaky test. We should evaluate if this test is really flaky and either fix the flake or remove the comment.

### What you expected to happen

We should have zero tolerance towards flaky tests and either fix them before committing or report them if we see them in the wild. I expect to be able to consistently run `make tests` without it failing and I expect to not see comments about flaky tests.

### Acceptance Criteria

GIVEN
the api repo is checked out
WHEN I
run make test
THEN I
never see errors

### How to reproduce it (as minimally and precisely as possible)

run `make tests` until it fails

### Anything else we need to know?

We haven't seen a flake, but since this was committed, we should investigate it.

### Environment

Revision of codebase: cf-k8s-api ([69945ad](https://github.com/cloudfoundry/cf-k8s-api/tree/69945ad))
Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5"
, Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4"
, Compiler:"gc", Platform:"linux/amd64"}
```
Cloud provider or hardware configuration:
```
❯ uname -a
Linux danailster-eirini-station 5.8.0-1035-gcp #37~20.04.1-Ubuntu SMP Thu Jun 17 16:04:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Others: N/A

**Comment by tcdowney** [comment]
cc @matt-royal to provide more info on that particular test and to share context about his flaky test strategy 😛

**Comment by matt-royal** [comment]
That test is definitely flakey. I haven't had the time to dig into it, but I left the comment to mark it for work later. Thank you for capturing the work here, @mnitchev.

**Comment by Birdrock** [comment]
@mnitchev we've tracked it down and will have a forthcoming fix.
