### ISSUE TITLE
Explore: Determine how we represent CF resource "guids" and name our K8s custom resources

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#2]
### CF for VMs Object Identification
Every Cloud Foundry API resource has a [globally unique ID (guid)](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#api-resource) which is used to uniquely identify it. **Many `GET` endpoints use the guid as the key for fetching an individual resource**. In CF for VMs these guids are ([usually](https://github.com/cloudfoundry/cloud_controller_ng/blob/b241622b890138c6e746f1407cc2cd7aec47cbbf/lib/sequel_plugins/vcap_guid.rb#L15)) [generated by the database](https://github.com/cloudfoundry/cloud_controller_ng/blob/4a23a419862ef9b7272f411a4435e33fc7305f30/db/helpers/uuid_function.rb) and are [random "Version 4" UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)).

### Kubernetes Object Identification
In Kubernetes objects can be identified by their GroupVersionKind + Name and Namespace*. Objects are fetched from the API by using this combination of properties.

* _Kubernetes objects also have [UIDs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids), but you [cannot look an object up in the K8s API by these](https://github.com/kubernetes/kubernetes/pull/76870#issuecomment-485559299)._

## Explore

We think there might be benefits to moving away from the random UUID structure for our resource "guids" and add some additional information to them such as org or space identifier to help implement some of the APIs in our shim. For example, if a user hits `GET /v3/packages/2802657a-f461-4171-bb97-b2004edb8003` and we have a Package names `2802657a-f461-4171-bb97-b2004edb8003` how will the shim know what namespace to look for that Package in? If we incorporated other information in there, and made it something like "org-name-space-name-2802657a" the shim might be able to make some assumptions about where the Package lives.

Questions to answer:
* Is there value in including additional information in our CR resource names? If so, what information should we include?
  * What are the benefits to changing the guid?
* Would any CF clients break if we change the guid format in our shim?
  * Look into the CF CLI, Java client, web GUIs

cc @Birdrock who wrote our original investigation story for this and may have additional context

**Comment by heycait** [comment]
Apps Manager doesn't do any GUID validation.

As pointed out by @tcdowney, [app-usage-service](https://github.com/pivotal-cf/app-usage-service/blob/d0445ba9e51d6428c54de10fb2960e081ebf5892/db/schema.rb#L19) cares bout the GUID length in the DB.

**Comment by acosta11** [comment]
Similarly, the java client does not appear to do GUID validation beyond basic (un)marshalling on the json field as a string type.

https://github.com/cloudfoundry/cf-java-client/blob/190f26a296789b2b7928877b318c33981dbe8707/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/Resource.java#L36-L37

**Comment by heycait** [comment]
We would like to optimize for eventual consistency in etcd across namespaces, so we need to have a deterministic and unique name for our resources. The two options for this would be embedding the org/space name within the app name directly or hashing the org/space name information. There are tradeoffs with either decision about the GUID format.

On one hand, there might be sensitive information if we embed the org/space name directly in the app name itself. By not including this extra information, there will need to be more filtering implementation. This also applies with the hashed version of the org/space name. 

The other concern/UI issue with these options is that kubectl users could be surprised that the object they created has a different name then what they specified. This can be hidden by the CF K8s API and only the specified app name could be returned. In this case, we propose that the k8s object name contain the extra information while a label on the resource will provide a more intuitive interface for other clients or users to filter by.

**Comment by matt-royal** [comment]
One thing worth considering with this hashing solution: names in CF are mutable. This means that the hashed GUID for an App may be different later if its name changes. Ditto for the space and org names, though there the obvious solution seems to be that we use their GUIDs. However, if all resource GUIDs are based on mutable fields, then you end up with even the org and space GUIDs "changing" later on.

**Comment by kieron-dev** [comment]
I feel nervous about encoding information into GUIDs. A see risks down the line with customers using the API to change things on resources that are encoded in their GUIDs. For example, don't some users promote builds through from test into production so they are confident they are executing exactly what was tested? If a GUID encodes cluster and namespace IDs, and this promotion involves moving or copying an object between namespaces or clusters, then the GUID encoding logic breaks.

So then we might introduce an admission hook enforcing GUID uniqueness (how do we do this for multi-cluster??), which prevents copying a GUID, but forces a kubectl user to make up a GUID without knowledge of the encoding scheme. Or overwrites the GUID given by the user, which is strange behaviour.

Other solutions might be possible for identifying a resource by GUID alone across namespaces. For example the controller-runtime cache allows indexing of non-searchable fields, making them searchable. So you could go from a GUID to a namespaced resource in a single GET. This is all built-in when writing controllers, but it might be possible to borrow the cache for the shim.

**Comment by tcdowney** [comment]
Linking the doc that @gnovv and @acosta11 put together here as well:
https://docs.google.com/document/d/1lUZ1kyZpExJNOHhXkFp0tqkjLJgEFqUFSyTDOoKCXuk/edit

> I feel nervous about encoding information into GUIDs.

I agree. The fact that we know at least one example of an external system storing CF guids in a database and making an assumption on string length makes me nervous as well... it would be nice if we could keep the same format as CF for VMs for it.

> For example the controller-runtime cache allows indexing of non-searchable fields, making them searchable.
I imagine we have to re-instantiate the client on every request to the shim don't we with the `bearer` credentials? I don't see how the regular controller-runtime client cache can persist when the client is used like this? Full disclosure, I haven't investigated this, it just doesn't sound like it would work intuitively.

One suggestion @emalm had (which is mentioned in that doc above) is to maintain our own in-memory cache of guid->namespace mappings that the shim could maintain and be used across requests. That could help with the single resource `GET` concern.
