### ISSUE TITLE
API Client can create an App via `POST /v3/apps`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-api#3]
## Blockers and Pre-requisites
* The CFApp custom resource definition should already exist in https://github.com/cloudfoundry/cf-k8s-controllers/
* We should have decided how we want to handle resource guids/naming. See: #2 

## Description
**As a** client of the CF API
**I want** to be able to create a new CFApp resource on Kubernetes via the API shim
**So that** I can begin using CF on Kubernetes

The behavior of this endpoint should match the existing behavior of the [`POST /v3/apps` endpoint](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#create-an-app) in CF for VMs as closely as possible -- including the [error cases](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#common-errors).

## Acceptance Criteria / Scenarios

**GIVEN** I have the API shim running locally
**THEN** I can make perform the following scenarios

**NOTE**
* The generate App guid should align with what we decided in #2
* ~~We will deal with environment variables in a separate story. If environment variables are present in the request payload ignore them for now.~~ **UPDATE:** We ended up implementing environment variables in this story.

---

### Happy Path

**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "name": "my_app",
    "relationships": {
      "space": {
        "data": {
          "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
        }
      }
    }
  }'
```

**THEN** I can use `kubectl` to view a `CFApp` CR in the K8s namespace that corresponds with the CF Space I specified. 

**AND** I get back the following response

```json
HTTP/1.1 201 Created
Content-Type: application/json

{
  "guid": "1cb006ee-fb05-47e1-b541-c34179ddc446",
  "name": "my_app",
  "state": "STOPPED",
  "created_at": "2016-03-17T21:41:30Z",
  "updated_at": "2016-06-08T16:41:26Z",
  "lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": [],
      "stack": ""
    }
  },
  "relationships": {
    "space": {
      "data": {
        "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446"
    },
    "space": {
      "href": "https://api.example.org/v3/spaces/2f35885d-0c9d-4423-83ad-fd05066f8576"
    },
    "processes": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/processes"
    },
    "packages": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/packages"
    },
    "environment_variables": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/environment_variables"
    },
    "current_droplet": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/droplets/current"
    },
    "droplets": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/droplets"
    },
    "tasks": {},
    "start": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/actions/start",
      "method": "POST"
    },
    "stop": {
      "href": "https://api.example.org/v3/apps/1cb006ee-fb05-47e1-b541-c34179ddc446/actions/stop",
      "method": "POST"
    },
    "revisions": {},
    "deployed_revisions": {},
    "features": {}
  },
  "metadata": {
    "labels": {},
    "annotations": {}
  }
}
```

**NOTE** We will deal with the `lifecycle` field more while we work on the Staging track. For now let's leave it minimal with an unspecified `stack` (this isn't valid in CF for VMs, but let's see what happens) and the `buildpacks` array set to `null` for autodetection. We are currently only planning on supporting `buildpack` apps.

---

### Request is invalid (invalid request body)

**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d 'bad json'
```

**THEN** A `CFApp` CR is not created
**AND** I get back the following response

```json
HTTP/1.1 400 Bad Request

{
  "errors": [
    {
      "detail": "Request invalid due to parse error: invalid request body",
      "title": "CF-MessageParseError",
      "code": 1001
    }
  ]
}
```

---

### Request is invalid (invalid App name)

**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "name": 12345,  <------------- non-string value
    "relationships": {
      "space": {
        "data": {
          "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
        }
      }
    }
  }'
```

**THEN** A `CFApp` CR is not created
**AND** I get back the following response

```json
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Name must be a string",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### Request is invalid (invalid Env vars structure)

**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "name": "my_app",
    "environment_variables": [],
    "relationships": {
      "space": {
        "data": {
          "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
        }
      }
    }
  }'
```

**THEN** A `CFApp` CR is not created
**AND** I get back the following response

```json
HTTP/1.1 422 Unprocessable Entity

{
   "errors": [
      {
         "detail": "Environment variables must be an object",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

---

### Space does not exist

**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "name": "my_app",
    "relationships": {
      "space": {
        "data": {
          "guid": "fake-space-does-not-exist-guid"
        }
      }
    }
  }'
```

**THEN** A `CFApp` CR is not created
**AND** I get back the following response

```json
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "Invalid space. Ensure that the space exists and you have access to it.",
      "title": "CF-UnprocessableEntity",
      "code": 10008
    }
  ]
}
```

---

### App already exists in space

**NOTE:** Try and rely on the same validating webhook logic as https://github.com/cloudfoundry/cf-k8s-controllers/issues/8 if you can.

**GIVEN** I have an App "my_app" that already exists in my Space
**WHEN** I make the following request

```
curl "https://api.example.org/v3/apps" \
  -X POST \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json" \
  -d '{
    "name": "my_app",
    "relationships": {
      "space": {
        "data": {
          "guid": "2f35885d-0c9d-4423-83ad-fd05066f8576"
        }
      }
    }
  }'
```

**THEN** The existing `CFApp` CR is not updated
**AND** I get back the following response

```json
HTTP/1.1 422 Unprocessable Entity

{
  "errors": [
    {
      "detail": "App with the name 'my_app' already exists.",
      "title": "CF-UniquenessError",
      "code": 10016
    }
  ]
}
```

---

### Dev Notes
* Refer to the [Wiki page on code structure and patterns](https://github.com/cloudfoundry/cf-k8s-api/wiki/Code-Structure-and-Coding-Practices) since we'll be introducing message parsing and error handling for `POST`s for the first time in this story.
* Since Auth(n/z) work is coming in separate story, use a hard-coded `ServiceAccount` for auth for now. For this story the `ServiceAccount` should have the minimal set of permissions to update a `CFApp`. Consider https://github.com/cloudfoundry/cf-crd-explorations/blob/main/config/rbac/app_editor_role.yaml as an example.
* Docs: https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#create-an-app
* It might be worth claiming a CF for VMs environment and playing around with the endpoint there to get a feel for what you can and cannot do with it. The existing V3 API docs may not be comprehensive.
* The Cloud Controller [AppsController#create](https://github.com/cloudfoundry/cloud_controller_ng/blob/b241622b890138c6e746f1407cc2cd7aec47cbbf/app/controllers/v3/apps_controller.rb#L85) code is a good place to look to see what CF for VMs is doing under the hood

**Comment by tcdowney** [comment]
@gcapizzi @kieron-dev 

I don't want to block these stories on the lack of Auth(n/z) /

**Comment by tcdowney** [comment]
@gcapizzi @kieron-dev I'm writing these stories with the shim endpoint expecting placeholder `bearer` tokens and doing nothing with them. They also assume that spaces (and namespaces) have been set up. Just want to double check that I'm correct in my assumption that we can proceed with these types of stories as is and y'all are planning a future story for some token management and space endpoints?

**Comment by gcapizzi** [comment]
@tcdowney yes we will definitely have stories to handle authentication in the shim, as the CLI will be sending either tokens or cert pairs. I don't think it matters who works on the space endpoints, they're out of scope of our investigations but we could certainly work on them!

**Comment by gnovv** [comment]
Making a note here that we plan on implementing the OwnerReferences on the Controller side, not the Shim w.r.t the EnvSecrets

**Comment by gnovv** [comment]
Making a note the environment variables Secret that is created only has a label with the appGUID, it does not inherit the app's metadata labels and annotations.

**Comment by tcdowney** [comment]
Was doing some testing of this on CF for VMs and discovered that the `buildpacks` array in the lifecycle should be an empty array instead of `null`. Like this:

```
"lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": [],
      "stack": ""
    }
  }
```

I updated the story AC to match that.
