### ISSUE TITLE
[Feature]: Implement source code to image : POST /v3/packages/:guid/upload

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/cf-k8s-api#46]
### Blockers/Dependencies

**Blocked By** 
[[Explore]: Packaging source code as Carvel's imgpkg ](https://github.com/cloudfoundry/cf-k8s-api/issues/35)
[[Feature]: Shim API can handle package uploads](https://github.com/cloudfoundry/cf-k8s-api/issues/47)

### Background

Based on the recommendation from #35, implement source code into the recommended image format conversion.

**As** a CF CLI User
**I want** to be able to upload source code as a zip
**So that** I can stage the application to run on Kubernetes

### Acceptance Criteria

**GIVEN** I have the shim deployed to a cluster
**WHEN** I run the following curl
```
curl "http://api-shim.example.org/v3/packages/[guid]/upload" \
  -X POST \
  -F bits=@"path-to-app-source.zip" \
```
**AND** It finished uploading / conversion

-  **THEN** I get the `HTTP 200 OK` with the following response, ensure that the `Package.state` reflects the current condition of the package - Refer [package conditions to state mapping table](https://miro.com/app/board/o9J_lFiI8CU=/?moveToWidget=3074457361338757508&cot=14)

```
{
  "guid": "44f7c078-0934-470f-9883-4fcddc5b8f13",
  "type": "bits",
  "data": {
    "checksum": {
      "type": "sha256",
      "value": null
    },
    "error": null
  },
  "state": "PROCESSING_UPLOAD",
  "created_at": "2015-11-13T17:02:56Z",
  "updated_at": "2016-06-08T16:41:26Z",
  "relationships": {
    "app": {
      "data": {
        "guid": "1d3bf0ec-5806-43c4-b64e-8364dba1086a"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13"
    },
    "upload": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13/upload",
      "method": "POST"
    },
    "download": {
      "href": "https://api.example.org/v3/packages/44f7c078-0934-470f-9883-4fcddc5b8f13/download",
      "method": "GET"
    },
    "app": {
      "href": "https://api.example.org/v3/apps/1d3bf0ec-5806-43c4-b64e-8364dba1086a"
    }
  },
  "metadata": {
    "labels": { },
    "annotations": { }
  }
}
```

-  **THEN** I can `kubectl get cfpackages [guid] -o yaml` to see where the app source image was pushed to
   **AND** I can `docker pull` the image to verify that it contains the app source code
   **AND** I can verify that status conditions collectively reflect `successful` upload and conversion

### Dev Notes
- The pair working on this story can decide on the design/approach and get consensus from the team before implementation.
- Credentials to image registry is needed for upload. Registry credentials should be created as a secret on the cluster and provided as a `config` to the shim.   
- If required the pair can decide on documenting the decision in an ADR.
- One approach is to implement this as a separate service called `registry-service` or alternatively it could be to make it part of the api-shim itself. 
    - For MVP purposes, including the `registry-service` inside of the shim should be fine. It can be extracted later for performance concerns (occupying too many threads, etc). Once we need to scale, we can pull this functionality out into a separate service to prevent blocking from larger uploads.
    - If checksum is present, remove for MVP.
    - Use https://github.com/cloudfoundry/capi-k8s-release/tree/main/src/registry-buddy as a reference for testing packaging.

**This may be influenced by the output of https://github.com/cloudfoundry/cf-crd-explorations/issues/76, which may merge some resources. As a result, status may need to be updated to avoid collisions between previously separate resources.**

**Comment by matt-royal** [comment]
The WIP is here: https://github.com/cloudfoundry/cf-k8s-api/tree/package-upload-issue-46
